[theme]
primaryColor="#D46253"
backgroundColor="#DDE1DD"
secondaryBackgroundColor="#91aa95"
textColor="##333332"
font="sans serif"


[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
headless = true
port = 80
